Rails.application.routes.draw do
  get 'favourites/new'
  get 'favourites/create'
  get 'favourites/destroy'
  get 'listplaces/new'
  get 'listplaces/create'
  get 'listplaces/destroy'
  get 'places/show'
  get 'places/new'
  get 'places/create'
  get 'places/update'
  get 'places/edit'
  get 'places/destroy'
  get 'lists/index'
  get 'lists/show'
  get 'lists/new'
  get 'lists/create'
  get 'lists/update'
  get 'lists/edit'
  get 'lists/destroy'
  get 'users/show'
  get 'users/new'
  get 'users/create'
  get 'users/update'
  get 'users/edit'
  get 'users/destroy'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
